### ISSUE TITLE
Object dimensions in the semantic map

### ISSUE THREAD

**Issue by fairlight1337** [code-iai/iai_maps#23]
The collision environment requires correct object dimensions in the semantic map to properly populate MoveIt!'s internal planning scene. Both, the MoveIt! controllers and (perspectively) Giskard rely on that for collision avoidance (and detection, thereof).

Right now, only selected counter tops have dimensions defined. See the attached image for details:
![collisionenvironment](https://cloud.githubusercontent.com/assets/1122132/17137082/6d744e10-5339-11e6-8e2b-e8722913e932.png)

Green is correctly defined, red and grey are not.

This can evolve into a potential show-stopper. @bbrieber, how's your schedule? Would you be able to fill these details in? Alternatively, can you help, @gaya-?

**Comment by gaya-** [comment]
I can help with the same speed as anyone else as the dimensions of bounding boxes come from Blender. Anyone can open the Blender meshes of furniture and add some numbers into the owl. This is how I imagine the process but I have no experience in this.

**Comment by fairlight1337** [comment]
I meant more like whether you have time at the moment to help out, or if you're busy with higher priority issues at the moment.

**Comment by gaya-** [comment]
I see. I would prefer not to do it right now as I'm not using the semantic map with Giskard yet. If you're not doing environment articulation and are not planning to do it for the demo, we could ask @bbrieber to add 4 boxes for each of the areas and that would be it. I actually thought that that's already there.

**Comment by gaya-** [comment]
I mean, adding dimensions of 4 boxes would be a 10 min job, as opposed to modelling all the drawers, or, actually, the walls of the drawers all individually or smt.

**Comment by fairlight1337** [comment]
Yeah, I guess we'll have to go with that for now

**Comment by gaya-** [comment]
Most objects in the semantic map now have dimensions that come from their bounding boxes. Accessible through ``object_dimensions(Owlname, Depth, Width, Height)`` predicate.
