### ISSUE TITLE
the meshes of pizza demo utensils have wrong scale

### ISSUE THREAD

**Issue by gheorghelisca** [code-iai/iai_maps#28]
- i created an urdf for tool_holder and spoon_adapter and wanted to visualize them on rviz.
- it turned out that the mesh of the tool_holder is bigger than the meshes of the whole iai kitchen
- could you please double check the scale of the meshes

**Comment by fairlight1337** [comment]
I just merged the PR since it looked good; only saw this comment afterwards. Hope this doesn't affect you negatively.

**Comment by mgvargas** [comment]
I just checked the scale of the meshes and they look ok in Inventor, could you scale them in the URDF?
 <mesh filename="package://path/to/file/file.stl" scale="0.001 0.001 0.001"/>
should work.

**Comment by gheorghelisca** [comment]
yes, i think the issue was that the meshes were exported in centimetres and rviz interprets them as metres.
