### ISSUE TITLE
openEASE does not visualize kitchen map correctly 

### ISSUE THREAD

**Issue by asilx** [code-iai/iai_maps#43]
@gaya-  @artnie 
After updating iai_maps repo, the kitchen seems visualized wierdly in openEASE. May that be because of recent changes in colladas?

![screenshot from 2017-08-31 10 37 03](https://user-images.githubusercontent.com/1322774/29902363-b00f6986-8e38-11e7-8d8f-3c701018bd43.png)
![screenshot from 2017-08-31 10 37 21](https://user-images.githubusercontent.com/1322774/29902364-b3e21c0c-8e38-11e7-96b5-8cdd87f31b44.png)

**Comment by gaya-** [comment]
Hey Asil, this is definitely a result of recent changes. Is this a visualization of the URDF? In RViz it looks fine. Are you visualizing both collision and vision meshes? We added proper collision meshes to the drawers etc. so we can put objects in them. Can you turn off visualization of collision objects in openease?

**Comment by daniel86** [comment]
I identified the two commits that cause this and put a comment below them.
 @gaya- looks into fixing these.

**Comment by artnie** [comment]
https://github.com/code-iai/iai_maps/pull/47 should fix this.
