### ISSUE TITLE
Better naming of maps

### ISSUE THREAD

**Issue by knowrob** [code-iai/iai_maps#5]
The maps have names such as "map", "map2" or "map_restricted" that do not say much about their content or the date at which they were recorded.

**Comment by bbferka** [comment]
This is a very old comment, but I would like to clean a bit this repo, since we have several redundant maps/launch files etc. 

Question is, should we keep the maps that are obsolete? (e.g. map, map2 map3 are useless at the moment.

**Comment by fairlight1337** [comment]
IMO kick it if its useless, i.e. if the floor in the lab changed :).

Cheers

**Comment by airballking** [comment]
I also vote for deleting useless maps.

**Comment by bbferka** [comment]
Sorry for being quiet about this, I'll finnish cleaning this up, once I get a clean map for the chemlab side if the lab( i. e. The kawada is gone)

**Comment by gaya-** [comment]
Solved in https://github.com/code-iai/iai_maps/pull/17
