### ISSUE TITLE
iai_dlr_cutting introduces dependency on iai_cad_tools

### ISSUE THREAD

**Issue by gaya-** [code-iai/iai_maps#53]
@airballking Can we get rid of this dependency please? If I just want to use the ground map, rosdep install doesn't work anymore because of this iai_cad_downloader dependency. I don't think such a commonly used package as this should introduce any new dependencies.

**Comment by airballking** [comment]
@gaya- I'd like to document this dependency and avoid setting ```CATKIN_IGNORE```. 

How about adding a rosinstall file that grabs all the dependencies that cannot be fetched using rosdep? ```KnowRob``` and ```Giskard``` already have such an installation workflow, and it works fine.

**Comment by gaya-** [comment]
@airballking Well, as I mentioned, I am not using the iai_cad_downloader, so I don't see any reason why users of CRAM should be downloading it into their workspace. To be honest, I am not really sure if iai_dlr_cutting should be a part of this repo as it's a research project of only a small subset of people from IAI. But if you insist on having it here, I would prefer to stick to the way things are right now, i.e. having an extra branch that ignores this dependency for CRAM users, and the master branch being as it is with the dlr_cutting included. I will take care of my branch and make sure it's up to date myself, so it's not extra work for anybody.

**Comment by airballking** [comment]
Why should that package not be a part of this repo? What is the common denominator of this repository?

**Comment by gaya-** [comment]
That is a good question, to which I do not have a clear answer :).

**Comment by bbferka** [comment]
Just my two cents on this: I always liked iai_maps not having extra package dependencies; Such that you can put it in a clean workspace and it "_compiles_". i.e. iai_semantic_maps does not depend on any knowrob related stuff, although it clearly is a knowrob package. For me `iai_maps` is a repository that holds static files and nothing more.

**Comment by gaya-** [comment]
We can then do something similar to iai_semantic_maps for iai_dlr_cutting, not include the entry in package.xml but have a rosinstall for the people who use iai_dlr_cutting that pulls iai_cad_downloader.

**Comment by gaya-** [comment]
Solved with af17f7c6f7ff41daf7d2254fe70a81005ef0117c
